# Generated by Django 6.0.3 on 2026-08-04 10:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Untitled Download', max_length=500)),
                ('original_url', models.TextField(blank=True, default='')),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('file', 'Direct File'), ('image_pdf', 'Image / Document')], default='video', max_length=20)),
                ('format_label', models.CharField(default='mp4', max_length=50)),
                ('file_name', models.CharField(blank=True, default='', max_length=500)),
                ('file_path', models.CharField(blank=True, default='', max_length=1000)),
                ('file_size', models.BigIntegerField(default=0)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
