# Generated by Django 6.0.3 on 2026-08-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadrecord',
            name='client_ip',
            field=models.CharField(blank=True, default='', max_length=45),
        ),
        migrations.AddField(
            model_name='downloadrecord',
            name='user_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
